version: '3.1'

services:
  flask:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: flask
    command: gunicorn --bind localhost:8000 --workers 4 "app:app"
    volumes:
      - ./:/var/www
    networks:
      my-network:
        aliases:
          - flask-app

networks:
  my-network: